[package]
name = "move_yield_copilot"
version = "0.0.1"
authors = []

[addresses]
move_yield_copilot = "0x123"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/movementlabsxyz/aptos-core.git"
rev = "movement"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
